#!/usr/bin/env python3
"""Single source of truth for the GW1N-LV4QN88 pin assignment of GB DEVCART r2.

Writes r2/gw1n4_qn88.cst (FPGA constraints) and r2/hw/fpga_pins.json (used by the netlist
generator), so the FPGA build and the PCB can never disagree.

Package sides (QN88, pin 1 top-left, counter-clockwise): left 1-22, bottom 23-44, right 45-66,
top 67-88. Config pins kept dedicated: JTAGSEL_N 4, TMS 5, TCK 6, TDI 7, TDO 8, RECONFIG_N 9,
DONE 10, MODE1 87, MODE0 88. Power: see docs/r2-pinouts.json.
"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
LEFT = [3, 11, 13, 14, 15, 16, 17, 18, 19, 20]
BOTTOM = list(range(25, 43))
RIGHT_TOP = [47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 59, 60, 61, 62, 63,
             68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 79, 80, 81, 82, 83, 84, 85, 86]

pins: dict[str, int] = {}
# left: clock (GCLKT_6 on pin 11), USB UART, console-side control, chip enables
for name, pin in zip(["RAM_NCE", "CLK48", "CONS_PRESENT", "UART_RX", "UART_TX", "GB_NCS",
                      "GB_NRESET", "BUS_NOE", "BUS_DIR", "ROM_NCE"], LEFT):
    pins[name] = pin
# bottom: console address bus and strobes, facing the level shifters / edge fingers
for name, pin in zip([f"GB_A[{i}]" for i in range(16)] + ["GB_NWR", "GB_NRD"], BOTTOM):
    pins[name] = pin
# right + top: memory side, facing flash / F-RAM
mem = [f"CD[{i}]" for i in range(8)] + ["MEM_NOE", "ROM_NWE", "RAM_NWE"] + [f"MA[{i}]" for i in range(23)]
for name, pin in zip(mem, RIGHT_TOP):
    pins[name] = pin

assert len(pins) == 62 and len(set(pins.values())) == 62, len(pins)

with open(HERE.parent / "gw1n4_qn88.cst", "w") as f:
    f.write("// GB DEVCART r2 — GW1N-LV4QN88 pin constraints, generated by r2/hw/fpga_pins.py\n")
    f.write("// All banks VCCIO = 3.3 V. JTAG / MODE / DONE / RECONFIG_N kept dedicated.\n")
    for name, pin in pins.items():
        pull = " PULL_MODE=UP" if name in ("CONS_PRESENT",) else ""
        f.write(f'IO_LOC "{name}" {pin};\nIO_PORT "{name}" IO_TYPE=LVCMOS33{pull};\n')
json.dump(pins, open(HERE / "fpga_pins.json", "w"), indent=1)
print(f"wrote gw1n4_qn88.cst and hw/fpga_pins.json ({len(pins)} pins)")
