#!/usr/bin/env python3
"""GB DEVCART r2 netlist generator (FPGA + USB-C).

Writes, into the fabdesk project directory (default /home/user/fabdesk-projects/gb-devcart-r2):
  lib/gbdev2.kicad_sym, lib/gbdev2.pretty/GB_Cart_Edge_32.kicad_mod, circuit.netlist.json

Pin tables come from docs/r2-pinouts.json (datasheet-checked) and the FPGA assignment from
r2/hw/fpga_pins.json (generated by fpga_pins.py, shared with the FPGA constraints), so the board,
the bitstream and the parts list cannot drift apart.

Schematic note: fab_pcb places generated symbols on a fixed 4-column grid (35.56 x 30.48 mm). Symbols
with more than 12 pins per side are drawn with their pins at +/-19.05 mm, an x offset that no other
symbol or neighbouring column uses, so pins and labels of overlapping symbols can never coincide
(the r1 net-merge bug). Tall symbols are given their own column/row band below.

    python3 r2/hw/gen_r2.py [project_dir]
"""
import json
import os
import shutil
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
import layout_dmg as LAYOUT  # noqa: E402

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
PROJ = Path(sys.argv[1] if len(sys.argv) > 1 else "/home/user/fabdesk-projects/gb-devcart-r2-2")
LIB = PROJ / "lib"
(LIB / "gbdev2.pretty").mkdir(parents=True, exist_ok=True)
shutil.copy(HERE / "board.kicad_dru", PROJ / "board.kicad_dru")
shutil.copy(REPO / "lib/gbdev.pretty/GB_Cart_Edge_32_DMG.kicad_mod", LIB / "gbdev2.pretty/GB_Cart_Edge_32_DMG.kicad_mod")

PIN = json.load(open(REPO / "docs/r2-pinouts.json"))
FPGA_IO = json.load(open(HERE / "fpga_pins.json"))

# ------------------------------------------------------------------------------- symbols
def esc(n: str) -> str:
    return n.replace("#", "").replace("/", "_")

def sym(prefix, desc, pins, left=None):
    """pins: [(num, name, type)]; left: names on the left side (rest go right)."""
    if left is None:
        half = (len(pins) + 1) // 2
        L, R = pins[:half], pins[half:]
    else:
        L = [p for p in pins if p[1] in left]
        R = [p for p in pins if p[1] not in left]
    return (prefix, desc, L, R)

FPGA_FUNC = {}
fp = PIN["U_FPGA"]
for name, nums in fp["power_pins"].items():
    if isinstance(nums, list):
        for n in nums:
            FPGA_FUNC[n] = name
for name, n in fp["config_pins"].items():
    if isinstance(n, int):
        FPGA_FUNC[n] = name
for name, n in FPGA_IO.items():
    FPGA_FUNC[n] = name
assert len(FPGA_FUNC) == 88, len(FPGA_FUNC)
fpga_pins = [(str(n), FPGA_FUNC[n], "power_in" if FPGA_FUNC[n].startswith(("VCC", "VSS")) else "passive")
             for n in range(1, 89)] + [("89", "EP", "power_in")]

# ERC pin types: rails are driven by the edge connector (VCC, GND) and the LDO outputs (power_out);
# IC supply pins are power_in; supply inputs fed through diodes / USB VBUS are passive (no driver to
# check); signal pins are passive so straps to a rail are not flagged as output-vs-power conflicts.
POWER_IN = ("VCC", "VDD", "VSS", "GND", "VCCA", "VCCB")
def ptype(v):
    w = v.split()[0]
    if w == "VOUT":
        return "power_out"
    return "power_in" if w in POWER_IN else "passive"

def table(key):
    t = PIN[key]["pins"]
    return [(str(k), v, ptype(v)) for k, v in t.items() if k.isdigit() or k[0] in "AB" and k[1:].isdigit()]

SYMS = {
    "GB_Cart_Edge_32": ("J", "Game Boy cartridge edge, 32 fingers", None, None),
    "GW1N-LV4QN88": sym("U", "Gowin GW1N-4 FPGA, QFN-88", fpga_pins),
    "S29GL064N_TSOP48": sym("U", "64 Mbit 3 V NOR flash, x8 byte mode", table("U_ROM")),
    "FM28V020": sym("U", "256 Kbit 3 V parallel F-RAM", table("U_FRAM")),
    "74LVCH245": sym("U", "Octal bus transceiver, bus hold, 5 V tolerant", table("U_ADDR_BUF_bushold")),
    "SN74LVC8T245": sym("U", "8-bit dual-supply transceiver", table("U_DATA_XCVR")),
    "XC6206P332": sym("U", "3.3 V 200 mA LDO", table("U_LDO_3V3")),
    "ME6211C12": sym("U", "1.2 V 500 mA LDO", table("U_LDO_1V2")),
    "CH347F": sym("U", "USB HS to UART + JTAG bridge", [(k if k != "0/EP" else "29", v, ptype(v))
                                                      for k, v in PIN["U_USB_BRIDGE"]["pins"].items()]),
    "USB_C_2.0": sym("J", "USB-C receptacle, USB 2.0", [(k, v, "passive") for k, v in PIN["J_USB"]["pins"].items()
                                                       if k != "SH"] + [("SH", "SHIELD", "passive")]),
    "USBLC6-2SC6": sym("U", "USB ESD protection", table("U_ESD")),
    "Oscillator_4pin": sym("X", "48 MHz CMOS oscillator", [("1", "OE", "passive"), ("2", "GND", "power_in"),
                                                          ("3", "OUT", "output"), ("4", "VDD", "power_in")]),
    "Crystal_GND24": sym("Y", "Crystal, pads 2/4 GND", [("1", "1", "passive"), ("2", "GND", "passive"),
                                                       ("3", "3", "passive"), ("4", "GND", "passive")]),
    "D_Schottky": ("D", "Schottky diode", [("2", "A", "passive")], [("1", "K", "passive")]),
    "R": ("R", "Resistor", [("1", "~", "passive")], [("2", "~", "passive")]),
    "C": ("C", "Capacitor", [("1", "~", "passive")], [("2", "~", "passive")]),
    "TestPoint": ("TP", "Test point", [("1", "1", "passive")], []),
}
CONN_NAMES = ["VCC", "CLK", "~{WR}", "~{RD}", "~{CS}"] + [f"A{i}" for i in range(16)] + \
             [f"D{i}" for i in range(8)] + ["~{RESET}", "AUDIO_IN", "GND"]
CONN = [(str(i + 1), n, "power_out" if n in ("VCC", "GND") else "passive") for i, n in enumerate(CONN_NAMES)]
SYMS["GB_Cart_Edge_32"] = ("J", SYMS["GB_Cart_Edge_32"][1], CONN[:16], CONN[16:])

WIDTH = {}   # per-symbol pin x offset (set by the layout search below)
YSHIFT = {}  # per-symbol vertical pin offset, 0 or 1.27 mm (sets the pin-row parity)
FONT = "(effects (font (size 1.27 1.27)))"
def sym_text(name, v):
    prefix, desc, left, right = v
    rows = max(len(left), len(right))
    tall = rows > 12
    two_sided = bool(right)
    W = WIDTH.get(name, 19.05 if tall else (12.7 if two_sided else 5.08))
    hw = W - 2.54 if two_sided else 1.27
    y0 = 1.27 * (rows - 1)
    top = y0 + 2.54
    out = [f'  (symbol "{name}" (pin_names (offset 1.016)) (exclude_from_sim no) (in_bom yes) (on_board yes)',
           f'    (property "Reference" "{prefix}" (at 0 {top + 1.27:.3f} 0) {FONT})',
           f'    (property "Value" "{name}" (at 0 {-top - 1.27:.3f} 0) {FONT})',
           f'    (property "Footprint" "" (at 0 0 0) (effects (font (size 1.27 1.27)) (hide yes)))',
           f'    (property "Datasheet" "" (at 0 0 0) (effects (font (size 1.27 1.27)) (hide yes)))',
           f'    (property "Description" "{desc}" (at 0 0 0) (effects (font (size 1.27 1.27)) (hide yes)))',
           f'    (symbol "{name}_0_1" (rectangle (start {-hw:.3f} {top:.3f}) (end {hw:.3f} {-top:.3f}) '
           f'(stroke (width 0.254) (type default)) (fill (type background))))',
           f'    (symbol "{name}_1_1"']
    ys = YSHIFT.get(name, 0.0)
    for side, pins, x, rot in (("L", left, -W, 0), ("R", right, W, 180)):
        for i, (num, pn, t) in enumerate(pins):
            out.append(f'      (pin {t} line (at {x:.3f} {y0 - 2.54 * i + ys:.3f} {rot}) (length 2.54) '
                       f'(name "{pn}" {FONT}) (number "{num}" {FONT}))')
    out.append("    )\n  )")
    return "\n".join(out)


PINNO = {k: {} for k in SYMS}
for k, (_p, _d, L, R) in SYMS.items():
    for num, pn, _t in L + R:
        PINNO[k].setdefault(pn, []).append(num)
        PINNO[k][num] = [num]

# ------------------------------------------------------------------------------- components
FP = {
    "GW1N-LV4QN88": "Package_DFN_QFN:ArtInChip_QFN-88-1EP_10x10mm_P0.4mm_EP6.74x6.74mm",
    "S29GL064N_TSOP48": "Package_SO:TSOP-I-48_18.4x12mm_P0.5mm",
    "FM28V020": "Package_SO:SOIC-28W_7.5x17.9mm_P1.27mm",
    "74LVCH245": "Package_SO:TSSOP-20_4.4x6.5mm_P0.65mm",
    "SN74LVC8T245": "Package_SO:TSSOP-24_4.4x7.8mm_P0.65mm",
    "XC6206P332": "Package_TO_SOT_SMD:SOT-23",
    "ME6211C12": "Package_TO_SOT_SMD:SOT-23-5",
    "CH347F": "Package_DFN_QFN:QFN-28-1EP_4x4mm_P0.4mm_EP2.4x2.4mm",
    "USB_C_2.0": "Connector_USB:USB_C_Receptacle_HRO_TYPE-C-31-M-12",
    "USBLC6-2SC6": "Package_TO_SOT_SMD:SOT-23-6",
    "Oscillator_4pin": "Oscillator:Oscillator_SMD_Abracon_ASDMB-4Pin_2.5x2.0mm",
    "Crystal_GND24": "Crystal:Crystal_SMD_3225-4Pin_3.2x2.5mm",
    "D_Schottky": "Diode_SMD:D_SOD-123",
    "R": "Resistor_SMD:R_0603_1608Metric",
    "C": "Capacitor_SMD:C_0603_1608Metric",
    "TestPoint": "TestPoint:TestPoint_Pad_D1.5mm",
    "GB_Cart_Edge_32": "gbdev2:GB_Cart_Edge_32_DMG",
}
MPN = {  # part -> (MPN, Manufacturer, LCSC)
    "GW1N-LV4QN88": ("GW1N-LV4QN88C6/I5", "Gowin", "C31900351"),
    "S29GL064N_TSOP48": ("S29GL064N90TFI040", "Infineon (Spansion)", "C117907"),
    "FM28V020": ("FM28V020-SGTR", "Infineon (Cypress)", "C54935"),
    "74LVCH245": ("SN74LVCH245APWR", "Texas Instruments", "C352976"),
    "SN74LVC8T245": ("SN74LVC8T245PWR", "Texas Instruments", "C27643"),
    "XC6206P332": ("XC6206P332MR-G", "Torex", "C5446"),
    "ME6211C12": ("ME6211C12M5G-N", "MICRONE", "C236672"),
    "CH347F": ("CH347F", "WCH", "C18221627"),
    "USB_C_2.0": ("TYPE-C-31-M-12", "HRO", "C165948"),
    "USBLC6-2SC6": ("USBLC6-2SC6", "ST", "C7519"),
    "Oscillator_4pin": ("OT3EL89CJI-111YLC-48M", "YXC", "C7434936"),
    "Crystal_GND24": ("XXDCELNANF-8MHZ", "TAITIEN", "C367183"),
    "D_Schottky": ("B5819W SL", "CJ", "C8598"),
}
PASSIVE = {  # value -> LCSC (JLC Basic, 0603)
    "5.1k": "C23186", "4.7k": "C23162", "1k": "C21190", "10k": "C25804",
    "22pF": "C1653", "100nF": "C14663", "1uF": "C15849", "10uF": "C19702",
}

comps, PARTOF, nets, PLACE = [], {}, {}, {}

def add(ref, part, value=None, at=None, **fields):
    f = dict(fields)
    if part in MPN:
        f.update(MPN=MPN[part][0], Manufacturer=MPN[part][1], LCSC=MPN[part][2])
    elif part in ("R", "C") and value in PASSIVE:
        f["LCSC"] = PASSIVE[value]
    comps.append({"ref": ref, "value": value or part, "footprint": FP[part],
                  "fields": f, "libSource": {"lib": "gbdev2", "part": part}})
    PARTOF[ref] = part
    if at:
        PLACE[ref] = at

def pin(ref, name):
    nums = PINNO[PARTOF[ref]][name]
    return [(ref, n) for n in nums]

def conn(net, *ends):
    lst = nets.setdefault(net, [])
    for ref, name in ends:
        for r, n in pin(ref, name):
            lst.append({"ref": r, "pin": n})

# Order matters for the schematic grid: index i -> column i%4, row i//4. Tall symbols get their
# own column and are spaced 3+ rows apart in it.
small_first = []
def r(ref, value, a, b, at=None):  # resistor between nets a and b
    add(ref, "R", value, at); conn(a, (ref, "1")); conn(b, (ref, "2"))
def c(ref, value, a, at=None, b="GND"):
    add(ref, "C", value, at); conn(a, (ref, "1")); conn(b, (ref, "2"))

# row 0-1: small parts
r("R1", "10k", "EDGE_5V", "CONS_DIV", (6, 10)); r("R2", "10k", "CONS_DIV", "GND", (6, 12))
r("R3", "1k", "FPGA_MODE0", "GND", (3, 28)); r("R4", "1k", "FPGA_MODE1", "GND", (5, 28))
r("R5", "4.7k", "JTAG_TCK", "GND", (17, 12)); r("R6", "4.7k", "FPGA_DONE", "3V3", (19, 28))
r("R7", "10k", "FPGA_RECONFIG_N", "3V3", (17, 28)); r("R8", "4.7k", "FPGA_JTAGSEL_N", "3V3", (3, 14))
# rows 2..: tall symbols, one per column
add("U1", "GW1N-LV4QN88", "GW1N-LV4QN88", (12, 20))
add("U2", "S29GL064N_TSOP48", "S29GL064N", (34, 20))
add("U3", "FM28V020", "FM28V020", (50, 20))
add("U10", "CH347F", "CH347F", (21, 7))
# filler rows (small symbols) keep tall ones apart vertically
r("R9", "10k", "BUS_NOE", "3V3", (44, 30)); r("R10", "10k", "ROM_NCE", "3V3", (24, 13))
r("R11", "10k", "RAM_NCE", "3V3", (44, 12)); r("R12", "10k", "ROM_NWE", "3V3", (26, 13))
r("R13", "10k", "RAM_NWE", "3V3", (46, 12)); r("R14", "10k", "ROM_RESET_N", "3V3", (28, 13))
r("R15", "10k", "ROM_WP_N", "3V3", (30, 13)); r("R16", "10k", "CH347_RST_N", "3V3", (25, 4))
r("R17", "5.1k", "USB_CC1", "GND", (33, 7)); r("R18", "5.1k", "USB_CC2", "GND", (23, 3))
add("D1", "D_Schottky", "B5819W", (44, 4)); conn("EDGE_5V", ("D1", "A")); conn("VSYS", ("D1", "K"))
add("D2", "D_Schottky", "B5819W", (44, 7)); conn("USB_VBUS", ("D2", "A")); conn("VSYS", ("D2", "K"))
add("U8", "XC6206P332", "XC6206P332", (50, 4))
add("U9", "ME6211C12", "ME6211C12", (50, 8))
add("X1", "Oscillator_4pin", "48MHz", (4, 20))
add("Y1", "Crystal_GND24", "8MHz", (14, 4))
add("U11", "USBLC6-2SC6", "USBLC6-2SC6", (36, 4))
add("U4", "74LVCH245", "74LVCH245", (7, 36))
add("U5", "74LVCH245", "74LVCH245", (17, 36))
add("U6", "74LVCH245", "74LVCH245", (39, 36))
add("U7", "SN74LVC8T245", "SN74LVC8T245", (49, 36))
add("J2", "USB_C_2.0", "USB-C", (28, 3.5))
add("J1", "GB_Cart_Edge_32", "GB_Cart_Edge_32", (28, 50))

# decoupling / bulk / crystal caps
caps = [("C1", "100nF", "1V2", (9, 14)), ("C2", "100nF", "1V2", (16, 26)), ("C3", "100nF", "1V2", (18, 16)),
        ("C4", "100nF", "1V2", (6, 24)), ("C5", "100nF", "3V3", (8, 14)), ("C6", "100nF", "3V3", (18, 22)),
        ("C7", "100nF", "3V3", (12, 27)), ("C8", "100nF", "3V3", (6, 18)), ("C9", "100nF", "3V3", (14, 13)),
        ("C10", "10uF", "1V2", (54, 10)), ("C11", "10uF", "3V3", (54, 4)), ("C12", "1uF", "VSYS", (47, 2)),
        ("C13", "1uF", "3V3", (54, 7)), ("C14", "1uF", "1V2", (47, 10)), ("C15", "10uF", "VSYS", (40, 2)),
        ("C16", "100nF", "3V3", (24, 23)), ("C17", "100nF", "3V3", (50, 29)), ("C18", "100nF", "3V3", (7, 31)),
        ("C19", "100nF", "3V3", (17, 31)), ("C20", "100nF", "3V3", (39, 31)), ("C21", "100nF", "3V3", (46, 31)),
        ("C22", "100nF", "EDGE_5V", (53, 31)), ("C23", "100nF", "3V3", (24, 9)), ("C24", "100nF", "3V3", (2, 17)),
        ("C27", "100nF", "3V3", (18, 9))]
for ref, val, net, at in caps:
    c(ref, val, net, at)
c("C25", "22pF", "XTAL_XI", (11, 2)); c("C26", "22pF", "XTAL_XO", (17, 2))
for i, (name, at) in enumerate([("EDGE_5V", (52, 40)), ("3V3", (49, 40)), ("1V2", (46, 40)), ("GND", (43, 40)),
                                ("GB_CLK", (10, 40)), ("GB_AUDIO", (13, 40))], 1):
    add(f"TP{i}", "TestPoint", f"TP_{name}", at); conn(name, (f"TP{i}", "1"))

# ------------------------------------------------------------------------------- wiring
# edge connector: 5 V, GND, console bus (5 V side)
conn("EDGE_5V", ("J1", "VCC")); conn("GND", ("J1", "GND"))
conn("GB_CLK", ("J1", "CLK")); conn("GB_AUDIO", ("J1", "AUDIO_IN"))
for i in range(16):
    conn(f"GB5_A{i}", ("J1", f"A{i}"))
for i in range(8):
    conn(f"GB5_D{i}", ("J1", f"D{i}"))
for n5, pn in (("GB5_NWR", "~{WR}"), ("GB5_NRD", "~{RD}"), ("GB5_NCS", "~{CS}"), ("GB5_NRESET", "~{RESET}")):
    conn(n5, ("J1", pn))

# address/control buffers: A side = console (5 V tolerant inputs), B side = 3.3 V to the FPGA
for ref, srcs in (("U4", [f"GB5_A{i}" for i in range(8)]), ("U5", [f"GB5_A{i}" for i in range(8, 16)]),
                  ("U6", ["GB5_NWR", "GB5_NRD", "GB5_NCS", "GB5_NRESET", "GND", "GND", "GND", "GND"])):
    conn("3V3", (ref, "DIR"), (ref, "VCC")); conn("GND", (ref, "OE#"), (ref, "GND"))
    for k, src in enumerate(srcs, 1):
        conn(src, (ref, f"A{k}"))
dst = {"U4": [f"GB_A{i}" for i in range(8)], "U5": [f"GB_A{i}" for i in range(8, 16)],
       "U6": ["GB_NWR", "GB_NRD", "GB_NCS", "GB_NRESET"]}
for ref, names in dst.items():
    for k, nm in enumerate(names, 1):
        conn(nm, (ref, f"B{k}"))
# U6 B5..B8 (driven from grounded inputs) are left open: listed as no-connects below

# data transceiver: A = cart 3.3 V side, B = console 5 V side
conn("3V3", ("U7", "VCCA")); conn("EDGE_5V", ("U7", "VCCB")); conn("GND", ("U7", "GND"))
conn("BUS_DIR", ("U7", "DIR")); conn("BUS_NOE", ("U7", "OE#"))
for i in range(8):
    conn(f"CD{i}", ("U7", f"A{i + 1}")); conn(f"GB5_D{i}", ("U7", f"B{i + 1}"))

# FPGA
fpga_net = {name: name.replace("[", "").replace("]", "") for name in FPGA_IO}
fpga_net.update({"GB_A[%d]" % i: f"GB_A{i}" for i in range(16)})
fpga_net.update({"CD[%d]" % i: f"CD{i}" for i in range(8)})
fpga_net.update({"MA[%d]" % i: f"MA{i}" for i in range(23)})
fpga_net.update({"CONS_PRESENT": "CONS_DIV", "CLK48": "CLK48", "UART_RX": "UART_TO_FPGA", "UART_TX": "UART_TO_USB"})
for name, n in FPGA_IO.items():
    conn(fpga_net[name], ("U1", str(n)))
for name, nums in PIN["U_FPGA"]["power_pins"].items():
    if not isinstance(nums, list):
        continue
    net = {"VCC": "1V2", "VSS": "GND"}.get(name, "3V3")  # VCCIO0-3 and VCCX at 3.3 V
    for n in nums:
        conn(net, ("U1", str(n)))
conn("GND", ("U1", "89"))
cfg = PIN["U_FPGA"]["config_pins"]
for name, net in (("TMS", "JTAG_TMS"), ("TCK", "JTAG_TCK"), ("TDI", "JTAG_TDI"), ("TDO", "JTAG_TDO"),
                  ("MODE0", "FPGA_MODE0"), ("MODE1", "FPGA_MODE1"), ("DONE", "FPGA_DONE"),
                  ("RECONFIG_N", "FPGA_RECONFIG_N"), ("JTAGSEL_N", "FPGA_JTAGSEL_N")):
    conn(net, ("U1", str(cfg[name])))

# flash, x8 byte mode: MA0 -> A-1 (DQ15/A-1), MA1..MA22 -> A0..A21
conn("MA0", ("U2", "DQ15/A-1"))
for i in range(22):
    conn(f"MA{i + 1}", ("U2", f"A{i}"))
for i in range(8):
    conn(f"CD{i}", ("U2", f"DQ{i}"))
conn("ROM_NCE", ("U2", "CE#")); conn("MEM_NOE", ("U2", "OE#")); conn("ROM_NWE", ("U2", "WE#"))
conn("ROM_RESET_N", ("U2", "RESET#")); conn("ROM_WP_N", ("U2", "WP#/ACC"))
conn("GND", ("U2", "BYTE#"), ("U2", "VSS")); conn("3V3", ("U2", "VCC"))

# F-RAM: MA0..MA14
for i in range(15):
    conn(f"MA{i}", ("U3", f"A{i}"))
for i in range(8):
    conn(f"CD{i}", ("U3", f"DQ{i}"))
conn("RAM_NCE", ("U3", "CE#")); conn("MEM_NOE", ("U3", "OE#")); conn("RAM_NWE", ("U3", "WE#"))
conn("GND", ("U3", "VSS")); conn("3V3", ("U3", "VDD"))

# power: edge 5 V and USB VBUS OR'd through D1/D2 into VSYS -> 3.3 V -> 1.2 V
conn("VSYS", ("U8", "VIN")); conn("3V3", ("U8", "VOUT")); conn("GND", ("U8", "VSS"))
conn("3V3", ("U9", "VIN"), ("U9", "CE")); conn("1V2", ("U9", "VOUT")); conn("GND", ("U9", "VSS"))

# 48 MHz clock
conn("3V3", ("X1", "OE"), ("X1", "VDD")); conn("GND", ("X1", "GND")); conn("CLK48", ("X1", "OUT"))

# USB-C + ESD + CH347F
for p in ("A4", "A9", "B4", "B9"):
    conn("USB_VBUS", ("J2", p))
for p in ("A1", "A12", "B1", "B12", "SH"):
    conn("GND", ("J2", p))
conn("USB_CC1", ("J2", "A5")); conn("USB_CC2", ("J2", "B5"))
conn("USB_DP", ("J2", "A6"), ("J2", "B6")); conn("USB_DN", ("J2", "A7"), ("J2", "B7"))
conn("USB_DP", ("U11", "1"), ("U11", "6")); conn("USB_DN", ("U11", "3"), ("U11", "4"))
conn("USB_VBUS", ("U11", "5")); conn("GND", ("U11", "2"))
conn("XTAL_XI", ("U10", "XI"), ("Y1", "1")); conn("XTAL_XO", ("U10", "XO"), ("Y1", "3"))
conn("GND", ("Y1", "2"), ("Y1", "4"))
conn("CH347_RST_N", ("U10", "RST#"))
conn("3V3", ("U10", "VIO"), ("U10", "VCC")); conn("GND", ("U10", "GND"))  # GND = pin 20 + exposed pad 29
conn("USB_DP", ("U10", "UD+")); conn("USB_DN", ("U10", "UD-"))
conn("UART_TO_FPGA", ("U10", "TXD0")); conn("UART_TO_USB", ("U10", "RXD0"))
for sig in ("TCK", "TMS", "TDI", "TDO"):
    conn(f"JTAG_{sig}", ("U10", sig))


# ------------------------------------------------------------------------------- schematic collision check
# Reproduces fab_pcb's generated-schematic geometry (vendor/fab_pcb/packages/compile/src/schematic.ts):
# symbol i at (24 + (i%4)*28, 20 + (i//4)*24) x 1.27 mm; every connected pin gets a wire from its
# endpoint 5.08 mm to the LEFT and a global label at the wire end. KiCad joins anything that touches
# a wire (ends or middle) or a pin endpoint, so two nets merge if any of their points/segments touch.
G = 1.27
def sym_geom(part):
    _p, _d, L, R = SYMS[part]
    rows = max(len(L), len(R))
    W = WIDTH.get(part, 19.05 if rows > 12 else (12.7 if R else 5.08))
    y0 = 1.27 * (rows - 1) + YSHIFT.get(part, 0.0)
    pts = {}
    for i, (num, _n, _t) in enumerate(L):
        pts[num] = (-W, y0 - 2.54 * i)
    for i, (num, _n, _t) in enumerate(R):
        pts[num] = (W, y0 - 2.54 * i)
    return pts

def collisions(order):
    pin_net = {(nd["ref"], nd["pin"]): n for n, lst in nets.items() for nd in lst}
    segs = []   # (y, x0, x1, net)  horizontal segments in 0.01 mm units
    points = [] # (x, y, net)       pin endpoints (incl. unconnected ones: they still touch wires)
    for idx, ref in enumerate(order):
        sx, sy = (24 + (idx % 4) * 28) * G, (20 + (idx // 4) * 24) * G
        for num, (px, py) in sym_geom(PARTOF[ref]).items():
            x, y = round((sx + px) * 100), round((sy - py) * 100)
            net = pin_net.get((ref, num))
            points.append((x, y, net or f"NC:{ref}.{num}"))
            if net:
                segs.append((y, x - 508, x, net))
    bad = set()
    by_y = {}
    for seg in segs:
        by_y.setdefault(seg[0], []).append(seg)
    for y, lst in by_y.items():
        lst.sort(key=lambda t: t[1])
        for i in range(len(lst)):
            for j in range(i + 1, len(lst)):
                if lst[j][1] > lst[i][2]:
                    break
                if lst[i][3] != lst[j][3]:
                    bad.add(tuple(sorted((lst[i][3], lst[j][3]))))
    for x, y, net in points:
        for (sy_, x0, x1, n2) in by_y.get(y, []):
            if x0 <= x <= x1 and n2 != net:
                bad.add(tuple(sorted((net, n2))))
    return bad

# ------------------------------------------------------------------------------- checks + output
seen = {}
for net, lst in nets.items():
    for nd in lst:
        k = (nd["ref"], nd["pin"])
        assert k not in seen, f"pin {k} on {net} and {seen[k]}"
        seen[k] = net
noconn = []
for ref, part in PARTOF.items():
    for num, pn, _t in SYMS[part][2] + SYMS[part][3]:
        if (ref, num) not in seen:
            noconn.append({"ref": ref, "pin": num})
for n, lst in nets.items():
    if len(lst) < 2:
        print(f"warning: net {n} has a single pin {lst}")
# every unconnected pin must be expected
allowed_nc = {("U2", "RY/BY#"), ("U2", "DQ8"), ("U2", "DQ9"), ("U2", "DQ10"), ("U2", "DQ11"), ("U2", "DQ12"),
              ("U2", "DQ13"), ("U2", "DQ14")}
for d in noconn:
    name = next(pn for num, pn, _ in SYMS[PARTOF[d["ref"]]][2] + SYMS[PARTOF[d["ref"]]][3] if num == d["pin"])
    ok = (d["ref"], name) in allowed_nc or (d["ref"] == "U6" and name in ("B5", "B6", "B7", "B8")) \
        or (d["ref"] == "U10" and name not in ("XI", "XO", "RST#", "VIO", "VCC", "GND", "UD+", "UD-", "TXD0", "RXD0",
                                               "TCK", "TMS", "TDI", "TDO")) \
        or (d["ref"] == "J2" and name.startswith("SBU")) or (d["ref"] == "U9" and name == "NC")
    assert ok, f"unexpected unconnected pin {d['ref']}.{d['pin']} ({name})"

doc = {
    "netlist": {"components": comps, "nets": [{"name": n, "nodes": v} for n, v in nets.items()],
                "noConnects": noconn, "design": {"source": "gb-devcart r2", "tool": "r2/hw/gen_r2.py"}},
    "board": {
        # DMG cartridge outline (r2.1); placement in r2/hw/layout_dmg.py, rotations applied after
        # circuit_build with circuit_place (the netlist placement schema has no rotation)
        "outline": [{"x": x, "y": y} for x, y in LAYOUT.outline()], "copperLayers": 4,
        "rules": {"clearanceMm": 0.1, "trackWidthMm": 0.15, "viaDiameterMm": 0.5, "viaDrillMm": 0.3},  # 0.1: QFN-88 pad pitch; JLC 4-layer allows 0.09
        "holes": [{"x": x, "y": y, "diameterMm": d} for x, y, d in LAYOUT.HOLES],
        "placements": [{"ref": r_, "position": {"x": x, "y": y}} for r_, (x, y, _) in LAYOUT.LAYOUT.items()],
    },
    "libraries": [
        {"kind": "symbol", "nickname": "gbdev2", "uri": str(LIB / "gbdev2.kicad_sym"), "description": "GB devcart r2 symbols"},
        {"kind": "footprint", "nickname": "gbdev2", "uri": str(LIB / "gbdev2.pretty"), "description": "GB devcart r2 footprints"},
    ],
}
# Layout search: reorder components and tune per-symbol width / row parity until no two nets touch.
import random
rng = random.Random(2)
order = [c_["ref"] for c_ in comps]
WIDTHS = [7.62, 10.16, 12.7, 15.24, 17.78, 19.05, 20.32, 22.86, 25.4]
best = len(collisions(order))
for step in range(6000):
    if best == 0:
        break
    saved = (list(order), dict(WIDTH), dict(YSHIFT))
    move = rng.random()
    if move < 0.5:
        i, j = rng.randrange(len(order)), rng.randrange(len(order))
        order[i], order[j] = order[j], order[i]
    elif move < 0.8:
        part = rng.choice(list(SYMS))
        if SYMS[part][3]:  # two-sided symbols only
            WIDTH[part] = rng.choice(WIDTHS)
    else:
        part = rng.choice(list(SYMS))
        YSHIFT[part] = 1.27 - YSHIFT.get(part, 0.0)
    n = len(collisions(order))
    if n <= best:
        best = n
    else:
        order, saved_w, saved_y = saved
        WIDTH.clear(); WIDTH.update(saved_w); YSHIFT.clear(); YSHIFT.update(saved_y)
bad = collisions(order)
assert not bad, f"schematic layout search failed, collisions remain: {sorted(bad)}"
comps.sort(key=lambda c_: order.index(c_["ref"]))
print(f"schematic layout: 0 collisions after {step} search steps")
with open(LIB / "gbdev2.kicad_sym", "w") as f:
    f.write('(kicad_symbol_lib (version 20241209) (generator "gbdev2") (generator_version "1.0")\n')
    for k, v in SYMS.items():
        f.write(sym_text(k, v) + "\n")
    f.write(")\n")
assert set(LAYOUT.LAYOUT) == {c_["ref"] for c_ in comps}, set(LAYOUT.LAYOUT) ^ {c_["ref"] for c_ in comps}
assert not LAYOUT.problems(), LAYOUT.problems()
json.dump(doc, open(PROJ / "circuit.netlist.json", "w"), indent=1)
print(f"ok {len(comps)} components, {len(nets)} nets, {len(noconn)} no-connects -> {PROJ}")
